// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: flydigi.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConnectionType int32

const (
	ConnectionType_UNKNOWN  ConnectionType = 0
	ConnectionType_WIRELESS ConnectionType = 1
	ConnectionType_WIRED    ConnectionType = 2
)

// Enum value maps for ConnectionType.
var (
	ConnectionType_name = map[int32]string{
		0: "UNKNOWN",
		1: "WIRELESS",
		2: "WIRED",
	}
	ConnectionType_value = map[string]int32{
		"UNKNOWN":  0,
		"WIRELESS": 1,
		"WIRED":    2,
	}
)

func (x ConnectionType) Enum() *ConnectionType {
	p := new(ConnectionType)
	*p = x
	return p
}

func (x ConnectionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConnectionType) Descriptor() protoreflect.EnumDescriptor {
	return file_flydigi_proto_enumTypes[0].Descriptor()
}

func (ConnectionType) Type() protoreflect.EnumType {
	return &file_flydigi_proto_enumTypes[0]
}

func (x ConnectionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConnectionType.Descriptor instead.
func (ConnectionType) EnumDescriptor() ([]byte, []int) {
	return file_flydigi_proto_rawDescGZIP(), []int{0}
}

type GamepadInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DeviceId       int32                  `protobuf:"varint,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	BatteryPercent int32                  `protobuf:"varint,2,opt,name=battery_percent,json=batteryPercent,proto3" json:"battery_percent,omitempty"`
	ConnectionType ConnectionType         `protobuf:"varint,3,opt,name=connection_type,json=connectionType,proto3,enum=flydigi.ConnectionType" json:"connection_type,omitempty"`
	CpuType        string                 `protobuf:"bytes,4,opt,name=cpu_type,json=cpuType,proto3" json:"cpu_type,omitempty"`
	CpuName        string                 `protobuf:"bytes,5,opt,name=cpu_name,json=cpuName,proto3" json:"cpu_name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GamepadInfo) Reset() {
	*x = GamepadInfo{}
	mi := &file_flydigi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GamepadInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GamepadInfo) ProtoMessage() {}

func (x *GamepadInfo) ProtoReflect() protoreflect.Message {
	mi := &file_flydigi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GamepadInfo.ProtoReflect.Descriptor instead.
func (*GamepadInfo) Descriptor() ([]byte, []int) {
	return file_flydigi_proto_rawDescGZIP(), []int{0}
}

func (x *GamepadInfo) GetDeviceId() int32 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

func (x *GamepadInfo) GetBatteryPercent() int32 {
	if x != nil {
		return x.BatteryPercent
	}
	return 0
}

func (x *GamepadInfo) GetConnectionType() ConnectionType {
	if x != nil {
		return x.ConnectionType
	}
	return ConnectionType_UNKNOWN
}

func (x *GamepadInfo) GetCpuType() string {
	if x != nil {
		return x.CpuType
	}
	return ""
}

func (x *GamepadInfo) GetCpuName() string {
	if x != nil {
		return x.CpuName
	}
	return ""
}

type GamepadConfiguration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeftJoystick  *JoystickConfiguration `protobuf:"bytes,1,opt,name=left_joystick,json=leftJoystick,proto3" json:"left_joystick,omitempty"`
	RightJoystick *JoystickConfiguration `protobuf:"bytes,2,opt,name=right_joystick,json=rightJoystick,proto3" json:"right_joystick,omitempty"`
	LeftTrigger   *TriggerConfiguration  `protobuf:"bytes,3,opt,name=left_trigger,json=leftTrigger,proto3" json:"left_trigger,omitempty"`
	RightTrigger  *TriggerConfiguration  `protobuf:"bytes,4,opt,name=right_trigger,json=rightTrigger,proto3" json:"right_trigger,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GamepadConfiguration) Reset() {
	*x = GamepadConfiguration{}
	mi := &file_flydigi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GamepadConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GamepadConfiguration) ProtoMessage() {}

func (x *GamepadConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_flydigi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GamepadConfiguration.ProtoReflect.Descriptor instead.
func (*GamepadConfiguration) Descriptor() ([]byte, []int) {
	return file_flydigi_proto_rawDescGZIP(), []int{1}
}

func (x *GamepadConfiguration) GetLeftJoystick() *JoystickConfiguration {
	if x != nil {
		return x.LeftJoystick
	}
	return nil
}

func (x *GamepadConfiguration) GetRightJoystick() *JoystickConfiguration {
	if x != nil {
		return x.RightJoystick
	}
	return nil
}

func (x *GamepadConfiguration) GetLeftTrigger() *TriggerConfiguration {
	if x != nil {
		return x.LeftTrigger
	}
	return nil
}

func (x *GamepadConfiguration) GetRightTrigger() *TriggerConfiguration {
	if x != nil {
		return x.RightTrigger
	}
	return nil
}

type JoystickConfiguration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deadzone      int32                  `protobuf:"varint,1,opt,name=deadzone,proto3" json:"deadzone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoystickConfiguration) Reset() {
	*x = JoystickConfiguration{}
	mi := &file_flydigi_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoystickConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoystickConfiguration) ProtoMessage() {}

func (x *JoystickConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_flydigi_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoystickConfiguration.ProtoReflect.Descriptor instead.
func (*JoystickConfiguration) Descriptor() ([]byte, []int) {
	return file_flydigi_proto_rawDescGZIP(), []int{2}
}

func (x *JoystickConfiguration) GetDeadzone() int32 {
	if x != nil {
		return x.Deadzone
	}
	return 0
}

type TriggerConfiguration struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Mode:
	//
	//	*TriggerConfiguration_Default
	//	*TriggerConfiguration_Race
	//	*TriggerConfiguration_Recoil
	//	*TriggerConfiguration_Sniper
	//	*TriggerConfiguration_Lock
	//	*TriggerConfiguration_Vibration
	Mode          isTriggerConfiguration_Mode `protobuf_oneof:"mode"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerConfiguration) Reset() {
	*x = TriggerConfiguration{}
	mi := &file_flydigi_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerConfiguration) ProtoMessage() {}

func (x *TriggerConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_flydigi_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerConfiguration.ProtoReflect.Descriptor instead.
func (*TriggerConfiguration) Descriptor() ([]byte, []int) {
	return file_flydigi_proto_rawDescGZIP(), []int{3}
}

func (x *TriggerConfiguration) GetMode() isTriggerConfiguration_Mode {
	if x != nil {
		return x.Mode
	}
	return nil
}

func (x *TriggerConfiguration) GetDefault() *TriggerDefault {
	if x != nil {
		if x, ok := x.Mode.(*TriggerConfiguration_Default); ok {
			return x.Default
		}
	}
	return nil
}

func (x *TriggerConfiguration) GetRace() *TriggerRace {
	if x != nil {
		if x, ok := x.Mode.(*TriggerConfiguration_Race); ok {
			return x.Race
		}
	}
	return nil
}

func (x *TriggerConfiguration) GetRecoil() *TriggerRecoil {
	if x != nil {
		if x, ok := x.Mode.(*TriggerConfiguration_Recoil); ok {
			return x.Recoil
		}
	}
	return nil
}

func (x *TriggerConfiguration) GetSniper() *TriggerSniper {
	if x != nil {
		if x, ok := x.Mode.(*TriggerConfiguration_Sniper); ok {
			return x.Sniper
		}
	}
	return nil
}

func (x *TriggerConfiguration) GetLock() *TriggerLock {
	if x != nil {
		if x, ok := x.Mode.(*TriggerConfiguration_Lock); ok {
			return x.Lock
		}
	}
	return nil
}

func (x *TriggerConfiguration) GetVibration() *TriggerVibration {
	if x != nil {
		if x, ok := x.Mode.(*TriggerConfiguration_Vibration); ok {
			return x.Vibration
		}
	}
	return nil
}

type isTriggerConfiguration_Mode interface {
	isTriggerConfiguration_Mode()
}

type TriggerConfiguration_Default struct {
	Default *TriggerDefault `protobuf:"bytes,10,opt,name=default,proto3,oneof"`
}

type TriggerConfiguration_Race struct {
	Race *TriggerRace `protobuf:"bytes,11,opt,name=race,proto3,oneof"`
}

type TriggerConfiguration_Recoil struct {
	Recoil *TriggerRecoil `protobuf:"bytes,12,opt,name=recoil,proto3,oneof"`
}

type TriggerConfiguration_Sniper struct {
	Sniper *TriggerSniper `protobuf:"bytes,13,opt,name=sniper,proto3,oneof"`
}

type TriggerConfiguration_Lock struct {
	Lock *TriggerLock `protobuf:"bytes,14,opt,name=lock,proto3,oneof"`
}

type TriggerConfiguration_Vibration struct {
	Vibration *TriggerVibration `protobuf:"bytes,15,opt,name=vibration,proto3,oneof"`
}

func (*TriggerConfiguration_Default) isTriggerConfiguration_Mode() {}

func (*TriggerConfiguration_Race) isTriggerConfiguration_Mode() {}

func (*TriggerConfiguration_Recoil) isTriggerConfiguration_Mode() {}

func (*TriggerConfiguration_Sniper) isTriggerConfiguration_Mode() {}

func (*TriggerConfiguration_Lock) isTriggerConfiguration_Mode() {}

func (*TriggerConfiguration_Vibration) isTriggerConfiguration_Mode() {}

type TriggerDefault struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerDefault) Reset() {
	*x = TriggerDefault{}
	mi := &file_flydigi_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerDefault) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerDefault) ProtoMessage() {}

func (x *TriggerDefault) ProtoReflect() protoreflect.Message {
	mi := &file_flydigi_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerDefault.ProtoReflect.Descriptor instead.
func (*TriggerDefault) Descriptor() ([]byte, []int) {
	return file_flydigi_proto_rawDescGZIP(), []int{4}
}

type TriggerRace struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InitialPos    int32                  `protobuf:"varint,1,opt,name=initialPos,proto3" json:"initialPos,omitempty"`
	Pressure      int32                  `protobuf:"varint,2,opt,name=pressure,proto3" json:"pressure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerRace) Reset() {
	*x = TriggerRace{}
	mi := &file_flydigi_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerRace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerRace) ProtoMessage() {}

func (x *TriggerRace) ProtoReflect() protoreflect.Message {
	mi := &file_flydigi_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerRace.ProtoReflect.Descriptor instead.
func (*TriggerRace) Descriptor() ([]byte, []int) {
	return file_flydigi_proto_rawDescGZIP(), []int{5}
}

func (x *TriggerRace) GetInitialPos() int32 {
	if x != nil {
		return x.InitialPos
	}
	return 0
}

func (x *TriggerRace) GetPressure() int32 {
	if x != nil {
		return x.Pressure
	}
	return 0
}

type TriggerRecoil struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	InitialPos      int32                  `protobuf:"varint,1,opt,name=initialPos,proto3" json:"initialPos,omitempty"`
	InitialStrength int32                  `protobuf:"varint,2,opt,name=initialStrength,proto3" json:"initialStrength,omitempty"`
	Intensity       int32                  `protobuf:"varint,3,opt,name=intensity,proto3" json:"intensity,omitempty"`
	Frequency       int32                  `protobuf:"varint,4,opt,name=frequency,proto3" json:"frequency,omitempty"`
	InputAfter      bool                   `protobuf:"varint,5,opt,name=inputAfter,proto3" json:"inputAfter,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *TriggerRecoil) Reset() {
	*x = TriggerRecoil{}
	mi := &file_flydigi_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerRecoil) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerRecoil) ProtoMessage() {}

func (x *TriggerRecoil) ProtoReflect() protoreflect.Message {
	mi := &file_flydigi_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerRecoil.ProtoReflect.Descriptor instead.
func (*TriggerRecoil) Descriptor() ([]byte, []int) {
	return file_flydigi_proto_rawDescGZIP(), []int{6}
}

func (x *TriggerRecoil) GetInitialPos() int32 {
	if x != nil {
		return x.InitialPos
	}
	return 0
}

func (x *TriggerRecoil) GetInitialStrength() int32 {
	if x != nil {
		return x.InitialStrength
	}
	return 0
}

func (x *TriggerRecoil) GetIntensity() int32 {
	if x != nil {
		return x.Intensity
	}
	return 0
}

func (x *TriggerRecoil) GetFrequency() int32 {
	if x != nil {
		return x.Frequency
	}
	return 0
}

func (x *TriggerRecoil) GetInputAfter() bool {
	if x != nil {
		return x.InputAfter
	}
	return false
}

type TriggerSniper struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InitialPos    int32                  `protobuf:"varint,1,opt,name=initialPos,proto3" json:"initialPos,omitempty"`
	Length        int32                  `protobuf:"varint,2,opt,name=length,proto3" json:"length,omitempty"`
	Pressure      int32                  `protobuf:"varint,3,opt,name=pressure,proto3" json:"pressure,omitempty"`
	InputAfter    bool                   `protobuf:"varint,4,opt,name=inputAfter,proto3" json:"inputAfter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerSniper) Reset() {
	*x = TriggerSniper{}
	mi := &file_flydigi_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerSniper) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerSniper) ProtoMessage() {}

func (x *TriggerSniper) ProtoReflect() protoreflect.Message {
	mi := &file_flydigi_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerSniper.ProtoReflect.Descriptor instead.
func (*TriggerSniper) Descriptor() ([]byte, []int) {
	return file_flydigi_proto_rawDescGZIP(), []int{7}
}

func (x *TriggerSniper) GetInitialPos() int32 {
	if x != nil {
		return x.InitialPos
	}
	return 0
}

func (x *TriggerSniper) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *TriggerSniper) GetPressure() int32 {
	if x != nil {
		return x.Pressure
	}
	return 0
}

func (x *TriggerSniper) GetInputAfter() bool {
	if x != nil {
		return x.InputAfter
	}
	return false
}

type TriggerLock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InitialPos    int32                  `protobuf:"varint,1,opt,name=initialPos,proto3" json:"initialPos,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerLock) Reset() {
	*x = TriggerLock{}
	mi := &file_flydigi_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerLock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerLock) ProtoMessage() {}

func (x *TriggerLock) ProtoReflect() protoreflect.Message {
	mi := &file_flydigi_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerLock.ProtoReflect.Descriptor instead.
func (*TriggerLock) Descriptor() ([]byte, []int) {
	return file_flydigi_proto_rawDescGZIP(), []int{8}
}

func (x *TriggerLock) GetInitialPos() int32 {
	if x != nil {
		return x.InitialPos
	}
	return 0
}

type TriggerVibration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Coefficient   int32                  `protobuf:"varint,1,opt,name=coefficient,proto3" json:"coefficient,omitempty"`
	Threshold     int32                  `protobuf:"varint,2,opt,name=threshold,proto3" json:"threshold,omitempty"`
	TravelRange   int32                  `protobuf:"varint,3,opt,name=travelRange,proto3" json:"travelRange,omitempty"`
	Frequency     int32                  `protobuf:"varint,4,opt,name=frequency,proto3" json:"frequency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerVibration) Reset() {
	*x = TriggerVibration{}
	mi := &file_flydigi_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerVibration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerVibration) ProtoMessage() {}

func (x *TriggerVibration) ProtoReflect() protoreflect.Message {
	mi := &file_flydigi_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerVibration.ProtoReflect.Descriptor instead.
func (*TriggerVibration) Descriptor() ([]byte, []int) {
	return file_flydigi_proto_rawDescGZIP(), []int{9}
}

func (x *TriggerVibration) GetCoefficient() int32 {
	if x != nil {
		return x.Coefficient
	}
	return 0
}

func (x *TriggerVibration) GetThreshold() int32 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *TriggerVibration) GetTravelRange() int32 {
	if x != nil {
		return x.TravelRange
	}
	return 0
}

func (x *TriggerVibration) GetFrequency() int32 {
	if x != nil {
		return x.Frequency
	}
	return 0
}

type LedsOff struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LedsOff) Reset() {
	*x = LedsOff{}
	mi := &file_flydigi_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LedsOff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedsOff) ProtoMessage() {}

func (x *LedsOff) ProtoReflect() protoreflect.Message {
	mi := &file_flydigi_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedsOff.ProtoReflect.Descriptor instead.
func (*LedsOff) Descriptor() ([]byte, []int) {
	return file_flydigi_proto_rawDescGZIP(), []int{10}
}

type LedsSteady struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Color         *Color                 `protobuf:"bytes,1,opt,name=color,proto3" json:"color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LedsSteady) Reset() {
	*x = LedsSteady{}
	mi := &file_flydigi_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LedsSteady) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedsSteady) ProtoMessage() {}

func (x *LedsSteady) ProtoReflect() protoreflect.Message {
	mi := &file_flydigi_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedsSteady.ProtoReflect.Descriptor instead.
func (*LedsSteady) Descriptor() ([]byte, []int) {
	return file_flydigi_proto_rawDescGZIP(), []int{11}
}

func (x *LedsSteady) GetColor() *Color {
	if x != nil {
		return x.Color
	}
	return nil
}

type LedsStreamlined struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Speed         float32                `protobuf:"fixed32,1,opt,name=speed,proto3" json:"speed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LedsStreamlined) Reset() {
	*x = LedsStreamlined{}
	mi := &file_flydigi_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LedsStreamlined) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedsStreamlined) ProtoMessage() {}

func (x *LedsStreamlined) ProtoReflect() protoreflect.Message {
	mi := &file_flydigi_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedsStreamlined.ProtoReflect.Descriptor instead.
func (*LedsStreamlined) Descriptor() ([]byte, []int) {
	return file_flydigi_proto_rawDescGZIP(), []int{12}
}

func (x *LedsStreamlined) GetSpeed() float32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

type LedsGradient struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Speed         float32                `protobuf:"fixed32,1,opt,name=speed,proto3" json:"speed,omitempty"`
	Colors        []*Color               `protobuf:"bytes,2,rep,name=colors,proto3" json:"colors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LedsGradient) Reset() {
	*x = LedsGradient{}
	mi := &file_flydigi_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LedsGradient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedsGradient) ProtoMessage() {}

func (x *LedsGradient) ProtoReflect() protoreflect.Message {
	mi := &file_flydigi_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedsGradient.ProtoReflect.Descriptor instead.
func (*LedsGradient) Descriptor() ([]byte, []int) {
	return file_flydigi_proto_rawDescGZIP(), []int{13}
}

func (x *LedsGradient) GetSpeed() float32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *LedsGradient) GetColors() []*Color {
	if x != nil {
		return x.Colors
	}
	return nil
}

type LedsConfiguration struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Brightness float32                `protobuf:"fixed32,1,opt,name=brightness,proto3" json:"brightness,omitempty"`
	// Types that are valid to be assigned to Leds:
	//
	//	*LedsConfiguration_Off
	//	*LedsConfiguration_Steady
	//	*LedsConfiguration_Streamlined
	//	*LedsConfiguration_Gradient
	Leds          isLedsConfiguration_Leds `protobuf_oneof:"leds"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LedsConfiguration) Reset() {
	*x = LedsConfiguration{}
	mi := &file_flydigi_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LedsConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedsConfiguration) ProtoMessage() {}

func (x *LedsConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_flydigi_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedsConfiguration.ProtoReflect.Descriptor instead.
func (*LedsConfiguration) Descriptor() ([]byte, []int) {
	return file_flydigi_proto_rawDescGZIP(), []int{14}
}

func (x *LedsConfiguration) GetBrightness() float32 {
	if x != nil {
		return x.Brightness
	}
	return 0
}

func (x *LedsConfiguration) GetLeds() isLedsConfiguration_Leds {
	if x != nil {
		return x.Leds
	}
	return nil
}

func (x *LedsConfiguration) GetOff() *LedsOff {
	if x != nil {
		if x, ok := x.Leds.(*LedsConfiguration_Off); ok {
			return x.Off
		}
	}
	return nil
}

func (x *LedsConfiguration) GetSteady() *LedsSteady {
	if x != nil {
		if x, ok := x.Leds.(*LedsConfiguration_Steady); ok {
			return x.Steady
		}
	}
	return nil
}

func (x *LedsConfiguration) GetStreamlined() *LedsStreamlined {
	if x != nil {
		if x, ok := x.Leds.(*LedsConfiguration_Streamlined); ok {
			return x.Streamlined
		}
	}
	return nil
}

func (x *LedsConfiguration) GetGradient() *LedsGradient {
	if x != nil {
		if x, ok := x.Leds.(*LedsConfiguration_Gradient); ok {
			return x.Gradient
		}
	}
	return nil
}

type isLedsConfiguration_Leds interface {
	isLedsConfiguration_Leds()
}

type LedsConfiguration_Off struct {
	Off *LedsOff `protobuf:"bytes,10,opt,name=off,proto3,oneof"`
}

type LedsConfiguration_Steady struct {
	Steady *LedsSteady `protobuf:"bytes,12,opt,name=steady,proto3,oneof"`
}

type LedsConfiguration_Streamlined struct {
	Streamlined *LedsStreamlined `protobuf:"bytes,13,opt,name=streamlined,proto3,oneof"`
}

type LedsConfiguration_Gradient struct {
	Gradient *LedsGradient `protobuf:"bytes,15,opt,name=gradient,proto3,oneof"`
}

func (*LedsConfiguration_Off) isLedsConfiguration_Leds() {}

func (*LedsConfiguration_Steady) isLedsConfiguration_Leds() {}

func (*LedsConfiguration_Streamlined) isLedsConfiguration_Leds() {}

func (*LedsConfiguration_Gradient) isLedsConfiguration_Leds() {}

type Color struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rgb           int32                  `protobuf:"varint,1,opt,name=rgb,proto3" json:"rgb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Color) Reset() {
	*x = Color{}
	mi := &file_flydigi_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Color) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Color) ProtoMessage() {}

func (x *Color) ProtoReflect() protoreflect.Message {
	mi := &file_flydigi_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Color.ProtoReflect.Descriptor instead.
func (*Color) Descriptor() ([]byte, []int) {
	return file_flydigi_proto_rawDescGZIP(), []int{15}
}

func (x *Color) GetRgb() int32 {
	if x != nil {
		return x.Rgb
	}
	return 0
}

var File_flydigi_proto protoreflect.FileDescriptor

const file_flydigi_proto_rawDesc = "" +
	"\n" +
	"\rflydigi.proto\x12\aflydigi\"\xcb\x01\n" +
	"\vGamepadInfo\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\x05R\bdeviceId\x12'\n" +
	"\x0fbattery_percent\x18\x02 \x01(\x05R\x0ebatteryPercent\x12@\n" +
	"\x0fconnection_type\x18\x03 \x01(\x0e2\x17.flydigi.ConnectionTypeR\x0econnectionType\x12\x19\n" +
	"\bcpu_type\x18\x04 \x01(\tR\acpuType\x12\x19\n" +
	"\bcpu_name\x18\x05 \x01(\tR\acpuName\"\xa8\x02\n" +
	"\x14GamepadConfiguration\x12C\n" +
	"\rleft_joystick\x18\x01 \x01(\v2\x1e.flydigi.JoystickConfigurationR\fleftJoystick\x12E\n" +
	"\x0eright_joystick\x18\x02 \x01(\v2\x1e.flydigi.JoystickConfigurationR\rrightJoystick\x12@\n" +
	"\fleft_trigger\x18\x03 \x01(\v2\x1d.flydigi.TriggerConfigurationR\vleftTrigger\x12B\n" +
	"\rright_trigger\x18\x04 \x01(\v2\x1d.flydigi.TriggerConfigurationR\frightTrigger\"3\n" +
	"\x15JoystickConfiguration\x12\x1a\n" +
	"\bdeadzone\x18\x01 \x01(\x05R\bdeadzone\"\xca\x02\n" +
	"\x14TriggerConfiguration\x123\n" +
	"\adefault\x18\n" +
	" \x01(\v2\x17.flydigi.TriggerDefaultH\x00R\adefault\x12*\n" +
	"\x04race\x18\v \x01(\v2\x14.flydigi.TriggerRaceH\x00R\x04race\x120\n" +
	"\x06recoil\x18\f \x01(\v2\x16.flydigi.TriggerRecoilH\x00R\x06recoil\x120\n" +
	"\x06sniper\x18\r \x01(\v2\x16.flydigi.TriggerSniperH\x00R\x06sniper\x12*\n" +
	"\x04lock\x18\x0e \x01(\v2\x14.flydigi.TriggerLockH\x00R\x04lock\x129\n" +
	"\tvibration\x18\x0f \x01(\v2\x19.flydigi.TriggerVibrationH\x00R\tvibrationB\x06\n" +
	"\x04mode\"\x10\n" +
	"\x0eTriggerDefault\"I\n" +
	"\vTriggerRace\x12\x1e\n" +
	"\n" +
	"initialPos\x18\x01 \x01(\x05R\n" +
	"initialPos\x12\x1a\n" +
	"\bpressure\x18\x02 \x01(\x05R\bpressure\"\xb5\x01\n" +
	"\rTriggerRecoil\x12\x1e\n" +
	"\n" +
	"initialPos\x18\x01 \x01(\x05R\n" +
	"initialPos\x12(\n" +
	"\x0finitialStrength\x18\x02 \x01(\x05R\x0finitialStrength\x12\x1c\n" +
	"\tintensity\x18\x03 \x01(\x05R\tintensity\x12\x1c\n" +
	"\tfrequency\x18\x04 \x01(\x05R\tfrequency\x12\x1e\n" +
	"\n" +
	"inputAfter\x18\x05 \x01(\bR\n" +
	"inputAfter\"\x83\x01\n" +
	"\rTriggerSniper\x12\x1e\n" +
	"\n" +
	"initialPos\x18\x01 \x01(\x05R\n" +
	"initialPos\x12\x16\n" +
	"\x06length\x18\x02 \x01(\x05R\x06length\x12\x1a\n" +
	"\bpressure\x18\x03 \x01(\x05R\bpressure\x12\x1e\n" +
	"\n" +
	"inputAfter\x18\x04 \x01(\bR\n" +
	"inputAfter\"-\n" +
	"\vTriggerLock\x12\x1e\n" +
	"\n" +
	"initialPos\x18\x01 \x01(\x05R\n" +
	"initialPos\"\x92\x01\n" +
	"\x10TriggerVibration\x12 \n" +
	"\vcoefficient\x18\x01 \x01(\x05R\vcoefficient\x12\x1c\n" +
	"\tthreshold\x18\x02 \x01(\x05R\tthreshold\x12 \n" +
	"\vtravelRange\x18\x03 \x01(\x05R\vtravelRange\x12\x1c\n" +
	"\tfrequency\x18\x04 \x01(\x05R\tfrequency\"\t\n" +
	"\aLedsOff\"2\n" +
	"\n" +
	"LedsSteady\x12$\n" +
	"\x05color\x18\x01 \x01(\v2\x0e.flydigi.ColorR\x05color\"'\n" +
	"\x0fLedsStreamlined\x12\x14\n" +
	"\x05speed\x18\x01 \x01(\x02R\x05speed\"L\n" +
	"\fLedsGradient\x12\x14\n" +
	"\x05speed\x18\x01 \x01(\x02R\x05speed\x12&\n" +
	"\x06colors\x18\x02 \x03(\v2\x0e.flydigi.ColorR\x06colors\"\x83\x02\n" +
	"\x11LedsConfiguration\x12\x1e\n" +
	"\n" +
	"brightness\x18\x01 \x01(\x02R\n" +
	"brightness\x12$\n" +
	"\x03off\x18\n" +
	" \x01(\v2\x10.flydigi.LedsOffH\x00R\x03off\x12-\n" +
	"\x06steady\x18\f \x01(\v2\x13.flydigi.LedsSteadyH\x00R\x06steady\x12<\n" +
	"\vstreamlined\x18\r \x01(\v2\x18.flydigi.LedsStreamlinedH\x00R\vstreamlined\x123\n" +
	"\bgradient\x18\x0f \x01(\v2\x15.flydigi.LedsGradientH\x00R\bgradientB\x06\n" +
	"\x04leds\"\x19\n" +
	"\x05Color\x12\x10\n" +
	"\x03rgb\x18\x01 \x01(\x05R\x03rgb*6\n" +
	"\x0eConnectionType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\f\n" +
	"\bWIRELESS\x10\x01\x12\t\n" +
	"\x05WIRED\x10\x02B*Z(github.com/pipe01/flydigictl/pkg/dbus/pbb\x06proto3"

var (
	file_flydigi_proto_rawDescOnce sync.Once
	file_flydigi_proto_rawDescData []byte
)

func file_flydigi_proto_rawDescGZIP() []byte {
	file_flydigi_proto_rawDescOnce.Do(func() {
		file_flydigi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_flydigi_proto_rawDesc), len(file_flydigi_proto_rawDesc)))
	})
	return file_flydigi_proto_rawDescData
}

var file_flydigi_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_flydigi_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_flydigi_proto_goTypes = []any{
	(ConnectionType)(0),           // 0: flydigi.ConnectionType
	(*GamepadInfo)(nil),           // 1: flydigi.GamepadInfo
	(*GamepadConfiguration)(nil),  // 2: flydigi.GamepadConfiguration
	(*JoystickConfiguration)(nil), // 3: flydigi.JoystickConfiguration
	(*TriggerConfiguration)(nil),  // 4: flydigi.TriggerConfiguration
	(*TriggerDefault)(nil),        // 5: flydigi.TriggerDefault
	(*TriggerRace)(nil),           // 6: flydigi.TriggerRace
	(*TriggerRecoil)(nil),         // 7: flydigi.TriggerRecoil
	(*TriggerSniper)(nil),         // 8: flydigi.TriggerSniper
	(*TriggerLock)(nil),           // 9: flydigi.TriggerLock
	(*TriggerVibration)(nil),      // 10: flydigi.TriggerVibration
	(*LedsOff)(nil),               // 11: flydigi.LedsOff
	(*LedsSteady)(nil),            // 12: flydigi.LedsSteady
	(*LedsStreamlined)(nil),       // 13: flydigi.LedsStreamlined
	(*LedsGradient)(nil),          // 14: flydigi.LedsGradient
	(*LedsConfiguration)(nil),     // 15: flydigi.LedsConfiguration
	(*Color)(nil),                 // 16: flydigi.Color
}
var file_flydigi_proto_depIdxs = []int32{
	0,  // 0: flydigi.GamepadInfo.connection_type:type_name -> flydigi.ConnectionType
	3,  // 1: flydigi.GamepadConfiguration.left_joystick:type_name -> flydigi.JoystickConfiguration
	3,  // 2: flydigi.GamepadConfiguration.right_joystick:type_name -> flydigi.JoystickConfiguration
	4,  // 3: flydigi.GamepadConfiguration.left_trigger:type_name -> flydigi.TriggerConfiguration
	4,  // 4: flydigi.GamepadConfiguration.right_trigger:type_name -> flydigi.TriggerConfiguration
	5,  // 5: flydigi.TriggerConfiguration.default:type_name -> flydigi.TriggerDefault
	6,  // 6: flydigi.TriggerConfiguration.race:type_name -> flydigi.TriggerRace
	7,  // 7: flydigi.TriggerConfiguration.recoil:type_name -> flydigi.TriggerRecoil
	8,  // 8: flydigi.TriggerConfiguration.sniper:type_name -> flydigi.TriggerSniper
	9,  // 9: flydigi.TriggerConfiguration.lock:type_name -> flydigi.TriggerLock
	10, // 10: flydigi.TriggerConfiguration.vibration:type_name -> flydigi.TriggerVibration
	16, // 11: flydigi.LedsSteady.color:type_name -> flydigi.Color
	16, // 12: flydigi.LedsGradient.colors:type_name -> flydigi.Color
	11, // 13: flydigi.LedsConfiguration.off:type_name -> flydigi.LedsOff
	12, // 14: flydigi.LedsConfiguration.steady:type_name -> flydigi.LedsSteady
	13, // 15: flydigi.LedsConfiguration.streamlined:type_name -> flydigi.LedsStreamlined
	14, // 16: flydigi.LedsConfiguration.gradient:type_name -> flydigi.LedsGradient
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_flydigi_proto_init() }
func file_flydigi_proto_init() {
	if File_flydigi_proto != nil {
		return
	}
	file_flydigi_proto_msgTypes[3].OneofWrappers = []any{
		(*TriggerConfiguration_Default)(nil),
		(*TriggerConfiguration_Race)(nil),
		(*TriggerConfiguration_Recoil)(nil),
		(*TriggerConfiguration_Sniper)(nil),
		(*TriggerConfiguration_Lock)(nil),
		(*TriggerConfiguration_Vibration)(nil),
	}
	file_flydigi_proto_msgTypes[14].OneofWrappers = []any{
		(*LedsConfiguration_Off)(nil),
		(*LedsConfiguration_Steady)(nil),
		(*LedsConfiguration_Streamlined)(nil),
		(*LedsConfiguration_Gradient)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_flydigi_proto_rawDesc), len(file_flydigi_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_flydigi_proto_goTypes,
		DependencyIndexes: file_flydigi_proto_depIdxs,
		EnumInfos:         file_flydigi_proto_enumTypes,
		MessageInfos:      file_flydigi_proto_msgTypes,
	}.Build()
	File_flydigi_proto = out.File
	file_flydigi_proto_goTypes = nil
	file_flydigi_proto_depIdxs = nil
}
