// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: flydigi.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConnectionType int32

const (
	ConnectionType_UNKNOWN  ConnectionType = 0
	ConnectionType_WIRELESS ConnectionType = 1
	ConnectionType_WIRED    ConnectionType = 2
)

// Enum value maps for ConnectionType.
var (
	ConnectionType_name = map[int32]string{
		0: "UNKNOWN",
		1: "WIRELESS",
		2: "WIRED",
	}
	ConnectionType_value = map[string]int32{
		"UNKNOWN":  0,
		"WIRELESS": 1,
		"WIRED":    2,
	}
)

func (x ConnectionType) Enum() *ConnectionType {
	p := new(ConnectionType)
	*p = x
	return p
}

func (x ConnectionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConnectionType) Descriptor() protoreflect.EnumDescriptor {
	return file_flydigi_proto_enumTypes[0].Descriptor()
}

func (ConnectionType) Type() protoreflect.EnumType {
	return &file_flydigi_proto_enumTypes[0]
}

func (x ConnectionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConnectionType.Descriptor instead.
func (ConnectionType) EnumDescriptor() ([]byte, []int) {
	return file_flydigi_proto_rawDescGZIP(), []int{0}
}

type GamepadInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DeviceId       int32                  `protobuf:"varint,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	BatteryPercent int32                  `protobuf:"varint,2,opt,name=battery_percent,json=batteryPercent,proto3" json:"battery_percent,omitempty"`
	ConnectionType ConnectionType         `protobuf:"varint,3,opt,name=connection_type,json=connectionType,proto3,enum=flydigi.ConnectionType" json:"connection_type,omitempty"`
	CpuType        string                 `protobuf:"bytes,4,opt,name=cpu_type,json=cpuType,proto3" json:"cpu_type,omitempty"`
	CpuName        string                 `protobuf:"bytes,5,opt,name=cpu_name,json=cpuName,proto3" json:"cpu_name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GamepadInfo) Reset() {
	*x = GamepadInfo{}
	mi := &file_flydigi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GamepadInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GamepadInfo) ProtoMessage() {}

func (x *GamepadInfo) ProtoReflect() protoreflect.Message {
	mi := &file_flydigi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GamepadInfo.ProtoReflect.Descriptor instead.
func (*GamepadInfo) Descriptor() ([]byte, []int) {
	return file_flydigi_proto_rawDescGZIP(), []int{0}
}

func (x *GamepadInfo) GetDeviceId() int32 {
	if x != nil {
		return x.DeviceId
	}
	return 0
}

func (x *GamepadInfo) GetBatteryPercent() int32 {
	if x != nil {
		return x.BatteryPercent
	}
	return 0
}

func (x *GamepadInfo) GetConnectionType() ConnectionType {
	if x != nil {
		return x.ConnectionType
	}
	return ConnectionType_UNKNOWN
}

func (x *GamepadInfo) GetCpuType() string {
	if x != nil {
		return x.CpuType
	}
	return ""
}

func (x *GamepadInfo) GetCpuName() string {
	if x != nil {
		return x.CpuName
	}
	return ""
}

type GamepadConfiguration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LeftJoystick  *JoystickConfiguration `protobuf:"bytes,1,opt,name=left_joystick,json=leftJoystick,proto3" json:"left_joystick,omitempty"`
	RightJoystick *JoystickConfiguration `protobuf:"bytes,2,opt,name=right_joystick,json=rightJoystick,proto3" json:"right_joystick,omitempty"`
	LeftTrigger   *TriggerConfiguration  `protobuf:"bytes,3,opt,name=left_trigger,json=leftTrigger,proto3" json:"left_trigger,omitempty"`
	RightTrigger  *TriggerConfiguration  `protobuf:"bytes,4,opt,name=right_trigger,json=rightTrigger,proto3" json:"right_trigger,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GamepadConfiguration) Reset() {
	*x = GamepadConfiguration{}
	mi := &file_flydigi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GamepadConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GamepadConfiguration) ProtoMessage() {}

func (x *GamepadConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_flydigi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GamepadConfiguration.ProtoReflect.Descriptor instead.
func (*GamepadConfiguration) Descriptor() ([]byte, []int) {
	return file_flydigi_proto_rawDescGZIP(), []int{1}
}

func (x *GamepadConfiguration) GetLeftJoystick() *JoystickConfiguration {
	if x != nil {
		return x.LeftJoystick
	}
	return nil
}

func (x *GamepadConfiguration) GetRightJoystick() *JoystickConfiguration {
	if x != nil {
		return x.RightJoystick
	}
	return nil
}

func (x *GamepadConfiguration) GetLeftTrigger() *TriggerConfiguration {
	if x != nil {
		return x.LeftTrigger
	}
	return nil
}

func (x *GamepadConfiguration) GetRightTrigger() *TriggerConfiguration {
	if x != nil {
		return x.RightTrigger
	}
	return nil
}

type JoystickConfiguration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Deadzone      int32                  `protobuf:"varint,1,opt,name=deadzone,proto3" json:"deadzone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoystickConfiguration) Reset() {
	*x = JoystickConfiguration{}
	mi := &file_flydigi_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoystickConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoystickConfiguration) ProtoMessage() {}

func (x *JoystickConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_flydigi_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoystickConfiguration.ProtoReflect.Descriptor instead.
func (*JoystickConfiguration) Descriptor() ([]byte, []int) {
	return file_flydigi_proto_rawDescGZIP(), []int{2}
}

func (x *JoystickConfiguration) GetDeadzone() int32 {
	if x != nil {
		return x.Deadzone
	}
	return 0
}

type VibrationBind struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          int32                  `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	MinFilter     int32                  `protobuf:"varint,2,opt,name=minFilter,proto3" json:"minFilter,omitempty"`
	Scale         int32                  `protobuf:"varint,3,opt,name=scale,proto3" json:"scale,omitempty"`
	TriggerParams []int32                `protobuf:"varint,4,rep,packed,name=triggerParams,proto3" json:"triggerParams,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VibrationBind) Reset() {
	*x = VibrationBind{}
	mi := &file_flydigi_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VibrationBind) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VibrationBind) ProtoMessage() {}

func (x *VibrationBind) ProtoReflect() protoreflect.Message {
	mi := &file_flydigi_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VibrationBind.ProtoReflect.Descriptor instead.
func (*VibrationBind) Descriptor() ([]byte, []int) {
	return file_flydigi_proto_rawDescGZIP(), []int{3}
}

func (x *VibrationBind) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *VibrationBind) GetMinFilter() int32 {
	if x != nil {
		return x.MinFilter
	}
	return 0
}

func (x *VibrationBind) GetScale() int32 {
	if x != nil {
		return x.Scale
	}
	return 0
}

func (x *VibrationBind) GetTriggerParams() []int32 {
	if x != nil {
		return x.TriggerParams
	}
	return nil
}

type TriggerConfiguration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AutoTrigger   *AutoTrigger           `protobuf:"bytes,1,opt,name=autoTrigger,proto3" json:"autoTrigger,omitempty"`
	TriggerMotor  *TriggerMotor          `protobuf:"bytes,2,opt,name=triggerMotor,proto3" json:"triggerMotor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerConfiguration) Reset() {
	*x = TriggerConfiguration{}
	mi := &file_flydigi_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerConfiguration) ProtoMessage() {}

func (x *TriggerConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_flydigi_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerConfiguration.ProtoReflect.Descriptor instead.
func (*TriggerConfiguration) Descriptor() ([]byte, []int) {
	return file_flydigi_proto_rawDescGZIP(), []int{4}
}

func (x *TriggerConfiguration) GetAutoTrigger() *AutoTrigger {
	if x != nil {
		return x.AutoTrigger
	}
	return nil
}

func (x *TriggerConfiguration) GetTriggerMotor() *TriggerMotor {
	if x != nil {
		return x.TriggerMotor
	}
	return nil
}

type AutoTrigger struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          int32                  `protobuf:"varint,1,opt,name=mode,proto3" json:"mode,omitempty"`
	VibrationBind *VibrationBind         `protobuf:"bytes,2,opt,name=vibrationBind,proto3" json:"vibrationBind,omitempty"`
	MixedBorder   int32                  `protobuf:"varint,3,opt,name=mixedBorder,proto3" json:"mixedBorder,omitempty"`
	MixedParams   []int32                `protobuf:"varint,4,rep,packed,name=mixedParams,proto3" json:"mixedParams,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AutoTrigger) Reset() {
	*x = AutoTrigger{}
	mi := &file_flydigi_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AutoTrigger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AutoTrigger) ProtoMessage() {}

func (x *AutoTrigger) ProtoReflect() protoreflect.Message {
	mi := &file_flydigi_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AutoTrigger.ProtoReflect.Descriptor instead.
func (*AutoTrigger) Descriptor() ([]byte, []int) {
	return file_flydigi_proto_rawDescGZIP(), []int{5}
}

func (x *AutoTrigger) GetMode() int32 {
	if x != nil {
		return x.Mode
	}
	return 0
}

func (x *AutoTrigger) GetVibrationBind() *VibrationBind {
	if x != nil {
		return x.VibrationBind
	}
	return nil
}

func (x *AutoTrigger) GetMixedBorder() int32 {
	if x != nil {
		return x.MixedBorder
	}
	return 0
}

func (x *AutoTrigger) GetMixedParams() []int32 {
	if x != nil {
		return x.MixedParams
	}
	return nil
}

type TriggerMotor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LineGear      *TriggerMotorSet       `protobuf:"bytes,1,opt,name=lineGear,proto3" json:"lineGear,omitempty"`
	MicrGear      *TriggerMotorSet       `protobuf:"bytes,2,opt,name=micrGear,proto3" json:"micrGear,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerMotor) Reset() {
	*x = TriggerMotor{}
	mi := &file_flydigi_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerMotor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerMotor) ProtoMessage() {}

func (x *TriggerMotor) ProtoReflect() protoreflect.Message {
	mi := &file_flydigi_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerMotor.ProtoReflect.Descriptor instead.
func (*TriggerMotor) Descriptor() ([]byte, []int) {
	return file_flydigi_proto_rawDescGZIP(), []int{6}
}

func (x *TriggerMotor) GetLineGear() *TriggerMotorSet {
	if x != nil {
		return x.LineGear
	}
	return nil
}

func (x *TriggerMotor) GetMicrGear() *TriggerMotorSet {
	if x != nil {
		return x.MicrGear
	}
	return nil
}

type TriggerMotorSet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          int32                  `protobuf:"varint,1,opt,name=type,proto3" json:"type,omitempty"`
	Min           int32                  `protobuf:"varint,2,opt,name=min,proto3" json:"min,omitempty"`
	Max           int32                  `protobuf:"varint,3,opt,name=max,proto3" json:"max,omitempty"`
	Filter        int32                  `protobuf:"varint,4,opt,name=filter,proto3" json:"filter,omitempty"`
	VibrLimit     int32                  `protobuf:"varint,5,opt,name=vibrLimit,proto3" json:"vibrLimit,omitempty"`
	Scale         int32                  `protobuf:"varint,6,opt,name=scale,proto3" json:"scale,omitempty"`
	TimeLimit     int32                  `protobuf:"varint,7,opt,name=timeLimit,proto3" json:"timeLimit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerMotorSet) Reset() {
	*x = TriggerMotorSet{}
	mi := &file_flydigi_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerMotorSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerMotorSet) ProtoMessage() {}

func (x *TriggerMotorSet) ProtoReflect() protoreflect.Message {
	mi := &file_flydigi_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerMotorSet.ProtoReflect.Descriptor instead.
func (*TriggerMotorSet) Descriptor() ([]byte, []int) {
	return file_flydigi_proto_rawDescGZIP(), []int{7}
}

func (x *TriggerMotorSet) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *TriggerMotorSet) GetMin() int32 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *TriggerMotorSet) GetMax() int32 {
	if x != nil {
		return x.Max
	}
	return 0
}

func (x *TriggerMotorSet) GetFilter() int32 {
	if x != nil {
		return x.Filter
	}
	return 0
}

func (x *TriggerMotorSet) GetVibrLimit() int32 {
	if x != nil {
		return x.VibrLimit
	}
	return 0
}

func (x *TriggerMotorSet) GetScale() int32 {
	if x != nil {
		return x.Scale
	}
	return 0
}

func (x *TriggerMotorSet) GetTimeLimit() int32 {
	if x != nil {
		return x.TimeLimit
	}
	return 0
}

type LedsOff struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LedsOff) Reset() {
	*x = LedsOff{}
	mi := &file_flydigi_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LedsOff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedsOff) ProtoMessage() {}

func (x *LedsOff) ProtoReflect() protoreflect.Message {
	mi := &file_flydigi_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedsOff.ProtoReflect.Descriptor instead.
func (*LedsOff) Descriptor() ([]byte, []int) {
	return file_flydigi_proto_rawDescGZIP(), []int{8}
}

type LedsSteady struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Color         *Color                 `protobuf:"bytes,1,opt,name=color,proto3" json:"color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LedsSteady) Reset() {
	*x = LedsSteady{}
	mi := &file_flydigi_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LedsSteady) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedsSteady) ProtoMessage() {}

func (x *LedsSteady) ProtoReflect() protoreflect.Message {
	mi := &file_flydigi_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedsSteady.ProtoReflect.Descriptor instead.
func (*LedsSteady) Descriptor() ([]byte, []int) {
	return file_flydigi_proto_rawDescGZIP(), []int{9}
}

func (x *LedsSteady) GetColor() *Color {
	if x != nil {
		return x.Color
	}
	return nil
}

type LedsStreamlined struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Speed         float32                `protobuf:"fixed32,1,opt,name=speed,proto3" json:"speed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LedsStreamlined) Reset() {
	*x = LedsStreamlined{}
	mi := &file_flydigi_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LedsStreamlined) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedsStreamlined) ProtoMessage() {}

func (x *LedsStreamlined) ProtoReflect() protoreflect.Message {
	mi := &file_flydigi_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedsStreamlined.ProtoReflect.Descriptor instead.
func (*LedsStreamlined) Descriptor() ([]byte, []int) {
	return file_flydigi_proto_rawDescGZIP(), []int{10}
}

func (x *LedsStreamlined) GetSpeed() float32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

type LedsGradient struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Speed         float32                `protobuf:"fixed32,1,opt,name=speed,proto3" json:"speed,omitempty"`
	Colors        []*Color               `protobuf:"bytes,2,rep,name=colors,proto3" json:"colors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LedsGradient) Reset() {
	*x = LedsGradient{}
	mi := &file_flydigi_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LedsGradient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedsGradient) ProtoMessage() {}

func (x *LedsGradient) ProtoReflect() protoreflect.Message {
	mi := &file_flydigi_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedsGradient.ProtoReflect.Descriptor instead.
func (*LedsGradient) Descriptor() ([]byte, []int) {
	return file_flydigi_proto_rawDescGZIP(), []int{11}
}

func (x *LedsGradient) GetSpeed() float32 {
	if x != nil {
		return x.Speed
	}
	return 0
}

func (x *LedsGradient) GetColors() []*Color {
	if x != nil {
		return x.Colors
	}
	return nil
}

type LedsConfiguration struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Brightness float32                `protobuf:"fixed32,1,opt,name=brightness,proto3" json:"brightness,omitempty"`
	// Types that are valid to be assigned to Leds:
	//
	//	*LedsConfiguration_Off
	//	*LedsConfiguration_Steady
	//	*LedsConfiguration_Streamlined
	//	*LedsConfiguration_Gradient
	Leds          isLedsConfiguration_Leds `protobuf_oneof:"leds"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LedsConfiguration) Reset() {
	*x = LedsConfiguration{}
	mi := &file_flydigi_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LedsConfiguration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LedsConfiguration) ProtoMessage() {}

func (x *LedsConfiguration) ProtoReflect() protoreflect.Message {
	mi := &file_flydigi_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LedsConfiguration.ProtoReflect.Descriptor instead.
func (*LedsConfiguration) Descriptor() ([]byte, []int) {
	return file_flydigi_proto_rawDescGZIP(), []int{12}
}

func (x *LedsConfiguration) GetBrightness() float32 {
	if x != nil {
		return x.Brightness
	}
	return 0
}

func (x *LedsConfiguration) GetLeds() isLedsConfiguration_Leds {
	if x != nil {
		return x.Leds
	}
	return nil
}

func (x *LedsConfiguration) GetOff() *LedsOff {
	if x != nil {
		if x, ok := x.Leds.(*LedsConfiguration_Off); ok {
			return x.Off
		}
	}
	return nil
}

func (x *LedsConfiguration) GetSteady() *LedsSteady {
	if x != nil {
		if x, ok := x.Leds.(*LedsConfiguration_Steady); ok {
			return x.Steady
		}
	}
	return nil
}

func (x *LedsConfiguration) GetStreamlined() *LedsStreamlined {
	if x != nil {
		if x, ok := x.Leds.(*LedsConfiguration_Streamlined); ok {
			return x.Streamlined
		}
	}
	return nil
}

func (x *LedsConfiguration) GetGradient() *LedsGradient {
	if x != nil {
		if x, ok := x.Leds.(*LedsConfiguration_Gradient); ok {
			return x.Gradient
		}
	}
	return nil
}

type isLedsConfiguration_Leds interface {
	isLedsConfiguration_Leds()
}

type LedsConfiguration_Off struct {
	Off *LedsOff `protobuf:"bytes,10,opt,name=off,proto3,oneof"`
}

type LedsConfiguration_Steady struct {
	Steady *LedsSteady `protobuf:"bytes,12,opt,name=steady,proto3,oneof"`
}

type LedsConfiguration_Streamlined struct {
	Streamlined *LedsStreamlined `protobuf:"bytes,13,opt,name=streamlined,proto3,oneof"`
}

type LedsConfiguration_Gradient struct {
	Gradient *LedsGradient `protobuf:"bytes,15,opt,name=gradient,proto3,oneof"`
}

func (*LedsConfiguration_Off) isLedsConfiguration_Leds() {}

func (*LedsConfiguration_Steady) isLedsConfiguration_Leds() {}

func (*LedsConfiguration_Streamlined) isLedsConfiguration_Leds() {}

func (*LedsConfiguration_Gradient) isLedsConfiguration_Leds() {}

type Color struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rgb           int32                  `protobuf:"varint,1,opt,name=rgb,proto3" json:"rgb,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Color) Reset() {
	*x = Color{}
	mi := &file_flydigi_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Color) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Color) ProtoMessage() {}

func (x *Color) ProtoReflect() protoreflect.Message {
	mi := &file_flydigi_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Color.ProtoReflect.Descriptor instead.
func (*Color) Descriptor() ([]byte, []int) {
	return file_flydigi_proto_rawDescGZIP(), []int{13}
}

func (x *Color) GetRgb() int32 {
	if x != nil {
		return x.Rgb
	}
	return 0
}

var File_flydigi_proto protoreflect.FileDescriptor

const file_flydigi_proto_rawDesc = "" +
	"\n" +
	"\rflydigi.proto\x12\aflydigi\"\xcb\x01\n" +
	"\vGamepadInfo\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\x05R\bdeviceId\x12'\n" +
	"\x0fbattery_percent\x18\x02 \x01(\x05R\x0ebatteryPercent\x12@\n" +
	"\x0fconnection_type\x18\x03 \x01(\x0e2\x17.flydigi.ConnectionTypeR\x0econnectionType\x12\x19\n" +
	"\bcpu_type\x18\x04 \x01(\tR\acpuType\x12\x19\n" +
	"\bcpu_name\x18\x05 \x01(\tR\acpuName\"\xa8\x02\n" +
	"\x14GamepadConfiguration\x12C\n" +
	"\rleft_joystick\x18\x01 \x01(\v2\x1e.flydigi.JoystickConfigurationR\fleftJoystick\x12E\n" +
	"\x0eright_joystick\x18\x02 \x01(\v2\x1e.flydigi.JoystickConfigurationR\rrightJoystick\x12@\n" +
	"\fleft_trigger\x18\x03 \x01(\v2\x1d.flydigi.TriggerConfigurationR\vleftTrigger\x12B\n" +
	"\rright_trigger\x18\x04 \x01(\v2\x1d.flydigi.TriggerConfigurationR\frightTrigger\"3\n" +
	"\x15JoystickConfiguration\x12\x1a\n" +
	"\bdeadzone\x18\x01 \x01(\x05R\bdeadzone\"}\n" +
	"\rVibrationBind\x12\x12\n" +
	"\x04type\x18\x01 \x01(\x05R\x04type\x12\x1c\n" +
	"\tminFilter\x18\x02 \x01(\x05R\tminFilter\x12\x14\n" +
	"\x05scale\x18\x03 \x01(\x05R\x05scale\x12$\n" +
	"\rtriggerParams\x18\x04 \x03(\x05R\rtriggerParams\"\x89\x01\n" +
	"\x14TriggerConfiguration\x126\n" +
	"\vautoTrigger\x18\x01 \x01(\v2\x14.flydigi.AutoTriggerR\vautoTrigger\x129\n" +
	"\ftriggerMotor\x18\x02 \x01(\v2\x15.flydigi.TriggerMotorR\ftriggerMotor\"\xa3\x01\n" +
	"\vAutoTrigger\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\x05R\x04mode\x12<\n" +
	"\rvibrationBind\x18\x02 \x01(\v2\x16.flydigi.VibrationBindR\rvibrationBind\x12 \n" +
	"\vmixedBorder\x18\x03 \x01(\x05R\vmixedBorder\x12 \n" +
	"\vmixedParams\x18\x04 \x03(\x05R\vmixedParams\"z\n" +
	"\fTriggerMotor\x124\n" +
	"\blineGear\x18\x01 \x01(\v2\x18.flydigi.TriggerMotorSetR\blineGear\x124\n" +
	"\bmicrGear\x18\x02 \x01(\v2\x18.flydigi.TriggerMotorSetR\bmicrGear\"\xb3\x01\n" +
	"\x0fTriggerMotorSet\x12\x12\n" +
	"\x04type\x18\x01 \x01(\x05R\x04type\x12\x10\n" +
	"\x03min\x18\x02 \x01(\x05R\x03min\x12\x10\n" +
	"\x03max\x18\x03 \x01(\x05R\x03max\x12\x16\n" +
	"\x06filter\x18\x04 \x01(\x05R\x06filter\x12\x1c\n" +
	"\tvibrLimit\x18\x05 \x01(\x05R\tvibrLimit\x12\x14\n" +
	"\x05scale\x18\x06 \x01(\x05R\x05scale\x12\x1c\n" +
	"\ttimeLimit\x18\a \x01(\x05R\ttimeLimit\"\t\n" +
	"\aLedsOff\"2\n" +
	"\n" +
	"LedsSteady\x12$\n" +
	"\x05color\x18\x01 \x01(\v2\x0e.flydigi.ColorR\x05color\"'\n" +
	"\x0fLedsStreamlined\x12\x14\n" +
	"\x05speed\x18\x01 \x01(\x02R\x05speed\"L\n" +
	"\fLedsGradient\x12\x14\n" +
	"\x05speed\x18\x01 \x01(\x02R\x05speed\x12&\n" +
	"\x06colors\x18\x02 \x03(\v2\x0e.flydigi.ColorR\x06colors\"\x83\x02\n" +
	"\x11LedsConfiguration\x12\x1e\n" +
	"\n" +
	"brightness\x18\x01 \x01(\x02R\n" +
	"brightness\x12$\n" +
	"\x03off\x18\n" +
	" \x01(\v2\x10.flydigi.LedsOffH\x00R\x03off\x12-\n" +
	"\x06steady\x18\f \x01(\v2\x13.flydigi.LedsSteadyH\x00R\x06steady\x12<\n" +
	"\vstreamlined\x18\r \x01(\v2\x18.flydigi.LedsStreamlinedH\x00R\vstreamlined\x123\n" +
	"\bgradient\x18\x0f \x01(\v2\x15.flydigi.LedsGradientH\x00R\bgradientB\x06\n" +
	"\x04leds\"\x19\n" +
	"\x05Color\x12\x10\n" +
	"\x03rgb\x18\x01 \x01(\x05R\x03rgb*6\n" +
	"\x0eConnectionType\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\f\n" +
	"\bWIRELESS\x10\x01\x12\t\n" +
	"\x05WIRED\x10\x02B*Z(github.com/pipe01/flydigictl/pkg/dbus/pbb\x06proto3"

var (
	file_flydigi_proto_rawDescOnce sync.Once
	file_flydigi_proto_rawDescData []byte
)

func file_flydigi_proto_rawDescGZIP() []byte {
	file_flydigi_proto_rawDescOnce.Do(func() {
		file_flydigi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_flydigi_proto_rawDesc), len(file_flydigi_proto_rawDesc)))
	})
	return file_flydigi_proto_rawDescData
}

var file_flydigi_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_flydigi_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_flydigi_proto_goTypes = []any{
	(ConnectionType)(0),           // 0: flydigi.ConnectionType
	(*GamepadInfo)(nil),           // 1: flydigi.GamepadInfo
	(*GamepadConfiguration)(nil),  // 2: flydigi.GamepadConfiguration
	(*JoystickConfiguration)(nil), // 3: flydigi.JoystickConfiguration
	(*VibrationBind)(nil),         // 4: flydigi.VibrationBind
	(*TriggerConfiguration)(nil),  // 5: flydigi.TriggerConfiguration
	(*AutoTrigger)(nil),           // 6: flydigi.AutoTrigger
	(*TriggerMotor)(nil),          // 7: flydigi.TriggerMotor
	(*TriggerMotorSet)(nil),       // 8: flydigi.TriggerMotorSet
	(*LedsOff)(nil),               // 9: flydigi.LedsOff
	(*LedsSteady)(nil),            // 10: flydigi.LedsSteady
	(*LedsStreamlined)(nil),       // 11: flydigi.LedsStreamlined
	(*LedsGradient)(nil),          // 12: flydigi.LedsGradient
	(*LedsConfiguration)(nil),     // 13: flydigi.LedsConfiguration
	(*Color)(nil),                 // 14: flydigi.Color
}
var file_flydigi_proto_depIdxs = []int32{
	0,  // 0: flydigi.GamepadInfo.connection_type:type_name -> flydigi.ConnectionType
	3,  // 1: flydigi.GamepadConfiguration.left_joystick:type_name -> flydigi.JoystickConfiguration
	3,  // 2: flydigi.GamepadConfiguration.right_joystick:type_name -> flydigi.JoystickConfiguration
	5,  // 3: flydigi.GamepadConfiguration.left_trigger:type_name -> flydigi.TriggerConfiguration
	5,  // 4: flydigi.GamepadConfiguration.right_trigger:type_name -> flydigi.TriggerConfiguration
	6,  // 5: flydigi.TriggerConfiguration.autoTrigger:type_name -> flydigi.AutoTrigger
	7,  // 6: flydigi.TriggerConfiguration.triggerMotor:type_name -> flydigi.TriggerMotor
	4,  // 7: flydigi.AutoTrigger.vibrationBind:type_name -> flydigi.VibrationBind
	8,  // 8: flydigi.TriggerMotor.lineGear:type_name -> flydigi.TriggerMotorSet
	8,  // 9: flydigi.TriggerMotor.micrGear:type_name -> flydigi.TriggerMotorSet
	14, // 10: flydigi.LedsSteady.color:type_name -> flydigi.Color
	14, // 11: flydigi.LedsGradient.colors:type_name -> flydigi.Color
	9,  // 12: flydigi.LedsConfiguration.off:type_name -> flydigi.LedsOff
	10, // 13: flydigi.LedsConfiguration.steady:type_name -> flydigi.LedsSteady
	11, // 14: flydigi.LedsConfiguration.streamlined:type_name -> flydigi.LedsStreamlined
	12, // 15: flydigi.LedsConfiguration.gradient:type_name -> flydigi.LedsGradient
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_flydigi_proto_init() }
func file_flydigi_proto_init() {
	if File_flydigi_proto != nil {
		return
	}
	file_flydigi_proto_msgTypes[12].OneofWrappers = []any{
		(*LedsConfiguration_Off)(nil),
		(*LedsConfiguration_Steady)(nil),
		(*LedsConfiguration_Streamlined)(nil),
		(*LedsConfiguration_Gradient)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_flydigi_proto_rawDesc), len(file_flydigi_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_flydigi_proto_goTypes,
		DependencyIndexes: file_flydigi_proto_depIdxs,
		EnumInfos:         file_flydigi_proto_enumTypes,
		MessageInfos:      file_flydigi_proto_msgTypes,
	}.Build()
	File_flydigi_proto = out.File
	file_flydigi_proto_goTypes = nil
	file_flydigi_proto_depIdxs = nil
}
